import { useState, useEffect } from 'react';
import axios from 'axios';
import { 
  Sparkles, 
  BrainCircuit, 
  ChevronDown, 
  Target,
  BookOpen,
  Code,
  Layers,
  Zap,
  MessageSquare,
  ThumbsUp,
  CornerDownRight,
  Send
} from 'lucide-react';

const FALLBACK_TOPICS = [
  { _id: '1', name: 'Arrays', slug: 'arrays' },
  { _id: '2', name: 'Dynamic Programming', slug: 'dynamic-programming' },
  { _id: '3', name: 'Graphs', slug: 'graphs' },
  { _id: '4', name: 'Strings', slug: 'strings' }
];

const ProblemPanel = ({ problem, setProblem, onProblemGenerated, problemId, topicParam, userStats }) => {
  const [topic, setTopic] = useState('Arrays & Hashing');
  const [difficulty, setDifficulty] = useState('Easy');
  const [topics, setTopics] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [nextDifficulty, setNextDifficulty] = useState(null);
  const [isTopicOpen, setIsTopicOpen] = useState(false);
  const [isDiffOpen, setIsDiffOpen] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

  // Tab state
  const [activeTab, setActiveTab] = useState('problem');
  const [commentText, setCommentText] = useState('');
  const [comments, setComments] = useState([
    {
      id: 1,
      user: 'CodeWizard',
      text: "The trick here is to use a hash map to store the frequency. It reduces the time complexity to O(n).",
      upvotes: 24,
      replies: [
        { id: 101, user: 'AlgoQueen', text: 'Exactly! Space complexity will be O(n) as well.', upvotes: 5 }
      ]
    },
    {
      id: 2,
      user: 'BitMaster',
      text: "Can we solve this using bit manipulation?",
      upvotes: 12,
      replies: []
    }
  ]);

  const handleUpvote = (commentId, replyId = null) => {
    setComments(comments.map(c => {
      if (replyId) {
        if (c.id === commentId) {
          return { ...c, replies: c.replies.map(r => r.id === replyId ? { ...r, upvotes: r.upvotes + 1 } : r) };
        }
        return c;
      }
      return c.id === commentId ? { ...c, upvotes: c.upvotes + 1 } : c;
    }));
  };

  const handleAddComment = () => {
    if (!commentText.trim()) return;
    setComments([{ id: Date.now(), user: 'You', text: commentText, upvotes: 0, replies: [] }, ...comments]);
    setCommentText('');
  };

  // Difficulty logic based on user stats
  useEffect(() => {
    if (userStats) {
      if (userStats.xp < 100) setDifficulty('Easy');
      else if (userStats.xp < 300) setDifficulty('Medium');
      else setDifficulty('Hard');
    }
  }, [userStats]);

  // Fetch topics from DB
  useEffect(() => {
    const fetchTopics = async () => {
      try {
        const token = localStorage.getItem('token');
        const config = token ? { headers: { Authorization: `Bearer ${token}` } } : {};
        const res = await axios.get('/api/topics', config);
        setTopics(Array.isArray(res.data) && res.data.length > 0 ? res.data : FALLBACK_TOPICS);
        if (topicParam && Array.isArray(res.data) && res.data.length > 0) {
          const foundTopic = res.data.find(t => t.slug === topicParam);
          if (foundTopic) setTopic(foundTopic.name);
        } else if (Array.isArray(res.data) && res.data.length > 0 && !problemId) {
          setTopic(res.data[0].name);
        }
      } catch (err) {
        console.error('Failed to fetch topics:', err);
        setTopics(FALLBACK_TOPICS);
      }
    };
    fetchTopics();
  }, [topicParam]);

  // Auto-generate problem if topicParam is provided
  useEffect(() => {
    const autoGenerate = async () => {
      if (topicParam && topic && !problemId && !problem && !hasAutoGenerated && !loading) {
        setHasAutoGenerated(true);
        await generateProblem();
      }
    };
    autoGenerate();
  }, [topicParam, topic, problemId, problem, hasAutoGenerated]);

  // Load problem by ID or recommendation (only if no topicParam)
  useEffect(() => {
    const fetchInitialProblem = async () => {
      if (topicParam) return;
      setLoading(true);
      setError(null);
      try {
        const token = localStorage.getItem('token');
        const config = { headers: { Authorization: `Bearer ${token}` } };
        if (problemId) {
          const res = await axios.get(`/api/problems/${problemId}`, config);
          setProblem(res.data);
          setTopic(res.data.topic?.name || res.data.topic);
          setDifficulty(res.data.difficulty);
        } else {
          const recRes = await axios.get('/api/adaptive/recommendations', config);
          if (recRes.data.recommendedProblem) {
            setProblem(recRes.data.recommendedProblem);
            setTopic(recRes.data.recommendedTopic?.name || 'Arrays & Hashing');
            setDifficulty(recRes.data.recommendedDifficulty || 'Easy');
          }
        }
      } catch (err) {
        setError(err.response?.data?.message || 'Failed to load problem');
      } finally {
        setLoading(false);
      }
    };
    fetchInitialProblem();
  }, [problemId, topicParam]);

  // Fetch next recommended difficulty when topic changes
  useEffect(() => {
    const fetchNextDifficulty = async () => {
      try {
        const token = localStorage.getItem('token');
        const config = { headers: { Authorization: `Bearer ${token}` } };
        const res = await axios.get(`/api/adaptive/next?topic=${encodeURIComponent(topic)}`, config);
        setNextDifficulty(res.data.difficulty);
      } catch (err) {
        console.error('Error fetching next difficulty:', err);
      }
    };
    if (topic) fetchNextDifficulty();
  }, [topic]);

  const generateProblem = async () => {
    setLoading(true);
    setError(null);
    try {
      const token = localStorage.getItem('token');
      const config = { headers: { Authorization: `Bearer ${token}` } };
      const res = await axios.post('/api/problems/generate', { topic, difficulty }, config);
      setProblem(res.data);
      if (onProblemGenerated) onProblemGenerated({ topic, difficulty, timestamp: Date.now() });
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to generate problem');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="h-full flex flex-col overflow-hidden">

      {/* ── Tabs ── */}
      <div className="shrink-0 px-5 pt-5">
        <div className="flex bg-white/5 p-1 rounded-xl border border-white/10">
          <button
            onClick={() => setActiveTab('problem')}
            className={`flex-1 flex items-center justify-center space-x-2 py-2 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'problem' ? 'bg-blue-600 text-white shadow-lg' : 'text-gray-400 hover:text-white'
            }`}
          >
            <BookOpen className="w-3.5 h-3.5" />
            <span>Problem</span>
          </button>
          <button
            onClick={() => setActiveTab('discussion')}
            className={`flex-1 flex items-center justify-center space-x-2 py-2 rounded-lg text-xs font-bold transition-all ${
              activeTab === 'discussion' ? 'bg-blue-600 text-white shadow-lg' : 'text-gray-400 hover:text-white'
            }`}
          >
            <MessageSquare className="w-3.5 h-3.5" />
            <span>Discussion</span>
          </button>
        </div>
      </div>

      {activeTab === 'problem' ? (
        <div className="flex-1 flex flex-col overflow-hidden min-h-0">

          {/* ── Generator controls (fixed height, never scrolls) ── */}
          <div className="shrink-0 px-5 pt-5 space-y-4">
            {/* Header */}
            <div className="flex items-center space-x-3">
              <div className="p-2.5 bg-blue-600/20 rounded-xl border border-blue-500/30">
                <Sparkles className="w-5 h-5 text-blue-400" />
              </div>
              <h2 className="text-xl font-bold text-white">AI Generator</h2>
            </div>

            {/* Topic Dropdown */}
            <div className="relative">
              <label className="text-[11px] font-bold text-gray-500 uppercase tracking-wider mb-2 block">
                Select Topic
              </label>
              <button
                onClick={() => setIsTopicOpen(!isTopicOpen)}
                className="w-full flex items-center justify-between px-4 py-3 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition-all text-left"
              >
                <div className="flex items-center space-x-3">
                  <BookOpen className="w-4 h-4 text-blue-400 shrink-0" />
                  <span className="text-sm font-medium truncate">{topic}</span>
                </div>
                <ChevronDown className={`w-4 h-4 text-gray-500 shrink-0 transition-transform ${isTopicOpen ? 'rotate-180' : ''}`} />
              </button>
              {isTopicOpen && (
                <div className="absolute top-full left-0 right-0 mt-2 py-2 bg-[#0a0a1f] border border-white/10 rounded-xl shadow-2xl z-50 max-h-56 overflow-y-auto custom-scrollbar">
                  {topics.map(t => (
                    <button
                      key={t._id}
                      onClick={() => { setTopic(t.name); setIsTopicOpen(false); }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-blue-600/20 hover:text-blue-400 transition-colors flex items-center space-x-3"
                    >
                      <div className="w-2 h-2 rounded-full bg-blue-500/50 shrink-0" />
                      <span>{t.name}</span>
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Difficulty Dropdown */}
            <div className="relative">
              <label className="text-[11px] font-bold text-gray-500 uppercase tracking-wider mb-2 block">
                Select Difficulty
              </label>
              <button
                onClick={() => setIsDiffOpen(!isDiffOpen)}
                className="w-full flex items-center justify-between px-4 py-3 bg-white/5 border border-white/10 rounded-xl hover:bg-white/10 transition-all text-left"
              >
                <div className="flex items-center space-x-3">
                  <Target className={`w-4 h-4 shrink-0 ${
                    difficulty === 'Easy' ? 'text-green-400' :
                    difficulty === 'Medium' ? 'text-yellow-400' : 'text-red-400'
                  }`} />
                  <span className="text-sm font-medium">{difficulty}</span>
                </div>
                <ChevronDown className={`w-4 h-4 text-gray-500 shrink-0 transition-transform ${isDiffOpen ? 'rotate-180' : ''}`} />
              </button>
              {isDiffOpen && (
                <div className="absolute top-full left-0 right-0 mt-2 py-2 bg-[#0a0a1f] border border-white/10 rounded-xl shadow-2xl z-50">
                  {['Easy', 'Medium', 'Hard'].map(d => (
                    <button
                      key={d}
                      onClick={() => { setDifficulty(d); setIsDiffOpen(false); }}
                      className="w-full px-4 py-2 text-left text-sm hover:bg-white/5 transition-colors flex items-center space-x-3"
                    >
                      <div className={`w-2 h-2 rounded-full shrink-0 ${
                        d === 'Easy' ? 'bg-green-500' : d === 'Medium' ? 'bg-yellow-500' : 'bg-red-500'
                      }`} />
                      <span>{d}</span>
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Generate Button */}
            <button
              onClick={generateProblem}
              disabled={loading}
              className="w-full group relative flex items-center justify-center space-x-3 py-3.5 bg-gradient-to-r from-blue-600 to-purple-600 rounded-xl font-bold text-white transition-all hover:scale-[1.02] active:scale-[0.98] disabled:opacity-50 disabled:scale-100 shadow-lg shadow-blue-600/20 overflow-hidden"
            >
              {loading ? (
                <>
                  <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span className="animate-pulse">Generating AI problem...</span>
                </>
              ) : (
                <>
                  <BrainCircuit className="w-5 h-5 group-hover:rotate-12 transition-transform" />
                  <span>Generate Problem</span>
                  <div className="absolute inset-0 bg-gradient-to-r from-white/0 via-white/20 to-white/0 -translate-x-full group-hover:animate-shimmer" />
                </>
              )}
            </button>

            {/* Adaptive Indicator */}
            {nextDifficulty && (
              <div className="flex items-center justify-between p-3 bg-white/5 border border-white/10 rounded-xl">
                <div className="flex items-center space-x-2">
                  <Zap className="w-4 h-4 text-yellow-400 shrink-0" />
                  <span className="text-[11px] font-bold text-gray-400 uppercase tracking-wider">Next Recommendation</span>
                </div>
                <span className={`text-xs font-bold px-2 py-1 rounded-lg shrink-0 ${
                  nextDifficulty === 'Easy' ? 'bg-green-500/10 text-green-400' :
                  nextDifficulty === 'Medium' ? 'bg-yellow-500/10 text-yellow-400' :
                  'bg-red-500/10 text-red-400'
                }`}>
                  {nextDifficulty}
                </span>
              </div>
            )}

            <div className="w-full h-px bg-white/10" />
          </div>

          {/* ── Problem display (scrollable) ── */}
          <div className="flex-1 overflow-y-auto custom-scrollbar px-5 pb-5 pt-2 min-h-0">
            {problem ? (
              <div className="space-y-5">
                {/* Title + badges */}
                <div>
                  <h3 className="text-xl font-bold text-white leading-snug mb-3">{problem.title}</h3>
                  <div className="flex flex-wrap gap-2">
                    <span className={`flex items-center space-x-1.5 px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider border ${
                      problem.difficulty === 'Easy' ? 'bg-green-500/10 text-green-400 border-green-500/20' :
                      problem.difficulty === 'Medium' ? 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20' :
                      'bg-red-500/10 text-red-400 border-red-500/20'
                    }`}>
                      <Target className="w-3 h-3" />
                      <span>{problem.difficulty}</span>
                    </span>
                    <span className="flex items-center space-x-1.5 px-3 py-1 rounded-full text-[10px] font-bold uppercase tracking-wider bg-blue-500/10 text-blue-400 border border-blue-500/20">
                      <Layers className="w-3 h-3" />
                      <span>{problem.topic}</span>
                    </span>
                  </div>
                </div>

                {/* Description */}
                <div className="space-y-2">
                  <h4 className="flex items-center space-x-2 text-gray-400 font-bold uppercase text-[10px] tracking-widest">
                    <BookOpen className="w-3.5 h-3.5" />
                    <span>Description</span>
                  </h4>
                  <div className="text-gray-300 text-sm leading-7 whitespace-pre-wrap bg-white/5 p-4 rounded-xl border border-white/5">
                    {problem.description}
                  </div>
                </div>

                {/* Examples */}
                {problem.examples && problem.examples.length > 0 && (
                  <div className="space-y-3">
                    <h4 className="flex items-center space-x-2 text-gray-400 font-bold uppercase text-[10px] tracking-widest">
                      <Code className="w-3.5 h-3.5" />
                      <span>Examples</span>
                    </h4>
                    {problem.examples.map((example, idx) => (
                      <div key={idx} className="bg-black/40 border border-white/5 rounded-xl overflow-hidden">
                        <div className="px-4 py-2 bg-white/5 border-b border-white/5">
                          <span className="text-[10px] font-bold text-gray-500">Example {idx + 1}</span>
                        </div>
                        <div className="p-4 space-y-3 font-mono text-xs">
                          <div className="space-y-1">
                            <span className="text-blue-400/80">Input:</span>
                            <div className="text-gray-400 bg-white/5 p-2 rounded break-all">{example.input}</div>
                          </div>
                          <div className="space-y-1">
                            <span className="text-green-400/80">Output:</span>
                            <div className="text-gray-400 bg-white/5 p-2 rounded break-all">{example.output}</div>
                          </div>
                          {example.explanation && (
                            <div className="pt-2 text-gray-500 italic border-t border-white/5 leading-relaxed">
                              // {example.explanation}
                            </div>
                          )}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ) : (
              !loading && (
                <div className="flex flex-col items-center justify-center py-16 text-center space-y-4">
                  <div className="p-6 bg-white/5 rounded-full border border-white/10 animate-pulse">
                    <Sparkles className="w-12 h-12 text-blue-500/30" />
                  </div>
                  <div className="space-y-1">
                    <p className="text-gray-400 font-medium">Ready to start?</p>
                    <p className="text-xs text-gray-600 max-w-[200px]">
                      Generate an AI-powered problem to begin your practice session.
                    </p>
                  </div>
                </div>
              )
            )}
          </div>
        </div>

      ) : (
        /* ── Discussion tab ── */
        <div className="flex-1 flex flex-col overflow-hidden min-h-0 px-5 pt-5 pb-5 gap-4">
          <div className="flex items-center justify-between shrink-0">
            <h3 className="text-xl font-bold">Community Discussion</h3>
            <span className="text-xs text-gray-500 font-bold uppercase tracking-widest">{comments.length} Comments</span>
          </div>

          {/* Comment Input */}
          <div className="relative shrink-0">
            <textarea
              value={commentText}
              onChange={(e) => setCommentText(e.target.value)}
              placeholder="Ask a question or share a tip..."
              className="w-full h-24 bg-white/5 border border-white/10 rounded-xl p-4 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500/50 transition-all resize-none"
            />
            <button
              onClick={handleAddComment}
              className="absolute bottom-3 right-3 p-2 bg-blue-600 rounded-lg hover:scale-105 transition-transform shadow-lg shadow-blue-600/20"
            >
              <Send className="w-4 h-4" />
            </button>
          </div>

          {/* Comments List */}
          <div className="flex-1 overflow-y-auto custom-scrollbar space-y-4 pr-1 min-h-0">
            {comments.map(comment => (
              <div key={comment.id} className="space-y-3">
                <div className="bg-white/5 border border-white/10 rounded-2xl p-4 space-y-3">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-2">
                      <img className="w-6 h-6 rounded-lg bg-gray-800" src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${comment.user}`} alt="" />
                      <span className="text-sm font-bold text-blue-400">{comment.user}</span>
                    </div>
                    <button
                      onClick={() => handleUpvote(comment.id)}
                      className="flex items-center space-x-1.5 text-xs text-gray-500 hover:text-white transition-colors"
                    >
                      <ThumbsUp className="w-3.5 h-3.5" />
                      <span className="font-bold">{comment.upvotes}</span>
                    </button>
                  </div>
                  <p className="text-sm text-gray-300 leading-relaxed">{comment.text}</p>
                </div>
                {comment.replies.map(reply => (
                  <div key={reply.id} className="flex space-x-3 ml-6">
                    <CornerDownRight className="w-4 h-4 text-gray-700 shrink-0 mt-2" />
                    <div className="flex-1 bg-white/5 border border-white/5 rounded-2xl p-4 space-y-2">
                      <div className="flex items-center justify-between">
                        <div className="flex items-center space-x-2">
                          <img className="w-5 h-5 rounded-lg bg-gray-800" src={`https://api.dicebear.com/7.x/avataaars/svg?seed=${reply.user}`} alt="" />
                          <span className="text-xs font-bold text-purple-400">{reply.user}</span>
                        </div>
                        <button
                          onClick={() => handleUpvote(comment.id, reply.id)}
                          className="flex items-center space-x-1.5 text-[10px] text-gray-600 hover:text-white transition-colors"
                        >
                          <ThumbsUp className="w-3 h-3" />
                          <span className="font-bold">{reply.upvotes}</span>
                        </button>
                      </div>
                      <p className="text-xs text-gray-400 leading-relaxed">{reply.text}</p>
                    </div>
                  </div>
                ))}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Error banner */}
      {error && (
        <div className="shrink-0 mx-5 mb-5 rounded-xl border border-red-500/30 bg-red-500/10 px-4 py-3 text-sm text-red-200">
          {error}
        </div>
      )}

      <style dangerouslySetInnerHTML={{ __html: `
        @keyframes shimmer { 100% { transform: translateX(100%); } }
        .animate-shimmer { animation: shimmer 2s infinite; }
        .custom-scrollbar::-webkit-scrollbar { width: 5px; }
        .custom-scrollbar::-webkit-scrollbar-track { background: transparent; }
        .custom-scrollbar::-webkit-scrollbar-thumb { background: rgba(255,255,255,0.06); border-radius: 10px; }
        .custom-scrollbar::-webkit-scrollbar-thumb:hover { background: rgba(255,255,255,0.12); }
      `}} />
    </div>
  );
};

export default ProblemPanel;
